import {defineField, defineType} from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Informações do site',
  type: 'document',
  initialValue: {
    priceOneHour: 'R$ 200',
    priceThirtyMinutes: 'R$ 160',
    whatsapp: '(11) 95282-8169',
    telephone: '(11) 2478-9218',
    weekdayHours: '12:00 às 20:00',
    saturdayHours: '12:00 às 18:00',
    sundayHours: 'Fechado',
    addressLine1: 'Rua Serra de Juréa, 442 - Tatuapé',
    addressLine2: 'São Paulo - SP',
    opportunitiesWhatsapp: '(11) 95282-8169',
  },
  groups: [
    {name: 'values', title: 'Valores', default: true},
    {name: 'contact', title: 'Contato'},
    {name: 'hours', title: 'Horários'},
    {name: 'location', title: 'Localização'},
    {name: 'opportunities', title: 'Oportunidades'},
  ],
  fields: [
    defineField({
      name: 'priceOneHour',
      title: 'Massagem completa — 1 hora',
      type: 'string',
      group: 'values',
      initialValue: 'R$ 200',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'priceThirtyMinutes',
      title: 'Massagem completa — 30 minutos',
      type: 'string',
      group: 'values',
      initialValue: 'R$ 160',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp',
      type: 'string',
      group: 'contact',
      initialValue: '(11) 95282-8169',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'telephone',
      title: 'Telefone',
      type: 'string',
      group: 'contact',
      initialValue: '(11) 2478-9218',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'weekdayHours',
      title: 'Segunda a sexta',
      type: 'string',
      group: 'hours',
      initialValue: '12:00 às 20:00',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'saturdayHours',
      title: 'Sábado',
      type: 'string',
      group: 'hours',
      initialValue: '12:00 às 18:00',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'sundayHours',
      title: 'Domingo',
      type: 'string',
      group: 'hours',
      initialValue: 'Fechado',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'addressLine1',
      title: 'Endereço — linha 1',
      type: 'string',
      group: 'location',
      initialValue: 'Rua Serra de Juréa, 442 - Tatuapé',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'addressLine2',
      title: 'Endereço — linha 2',
      type: 'string',
      group: 'location',
      initialValue: 'São Paulo - SP',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'opportunitiesWhatsapp',
      title: 'WhatsApp — Trabalhe Conosco',
      type: 'string',
      group: 'opportunities',
      initialValue: '(11) 95282-8169',
      description: 'Pode ser o mesmo número do atendimento ou outro número específico para candidatas.',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    prepare() {
      return {title: 'Informações do site', subtitle: 'Valores, contato, horários e endereço'}
    },
  },
})
